# Generated by Django 2.2.2 on 2019-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='MID',
        ),
        migrations.AddField(
            model_name='merchant',
            name='Password',
            field=models.CharField(default='password', help_text='Enter your Merchant ID code', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='Preshared',
            field=models.CharField(default='preshared key', help_text='Enter your Merchant ID code', max_length=50),
        ),
    ]
