# Generated by Django 2.2.3 on 2019-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20190624_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='hashmethod',
            field=models.CharField(default='SHA1', help_text='Select has method', max_length=14),
        ),
        migrations.AddField(
            model_name='merchant',
            name='resultdeliverymethod',
            field=models.CharField(default='POST', help_text='Select result delivery method', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='transactiontype',
            field=models.CharField(default='SALE', help_text='Select transaction type', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Password',
            field=models.CharField(default='password', help_text='Enter your password', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Preshared',
            field=models.CharField(default='preshared key', help_text='Enter your preshared key', max_length=50),
        ),
    ]
