# Generated by Django 2.2.3 on 2019-07-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20190710_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='hashmethod',
            new_name='HashMethod',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='resultdeliverymethod',
            new_name='ResultDeliveryMethod',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='transactiontype',
            new_name='TransactionType',
        ),
    ]
