# Generated by Django 2.2.3 on 2019-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20190715_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='HashMethod',
            field=models.CharField(choices=[('MD5', 'MD5'), ('SHA1', 'SHA1'), ('HMACMD5', 'HMACMD5'), ('HMACSHA1', 'HMACSHA1'), ('HMACSHA256', 'HMACSHA256'), ('HMACSHA512', 'HMACSHA512')], max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ResultDeliveryMethod',
            field=models.CharField(choices=[('POST', 'POST'), ('SERVER_PULL', 'SERVER_PULL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='TransactionType',
            field=models.CharField(default='SALE', help_text='Enter transaction type', max_length=50),
        ),
    ]
