# Generated by Django 2.2.3 on 2019-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_auto_20190719_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='HashMethod',
            field=models.CharField(default='SHA1', help_text='Select has method', max_length=14),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ResultDeliveryMethod',
            field=models.CharField(default='POST', help_text='Select result delivery method', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='TransactionType',
            field=models.CharField(default='SALE', help_text='Select transaction type', max_length=50),
        ),
    ]
